name: Update and Merge Data

on:
  schedule:
    - cron: '0 */2 * * *'  # ⏱ Runs every 2 Hours
  workflow_dispatch:        # 🖱️ Allows manual trigger

permissions:
  contents: write  # 🔐 REQUIRED to allow git push from GitHub Actions

jobs:
  update-data:
    runs-on: ubuntu-latest
    environment: .env  # 👈 Link to the environment where your vars are defined

    env:
      SHOPIFY_STORE: ${{ vars.SHOPIFY_STORE }}
      SHOPIFY_ACCESS_TOKEN: ${{ vars.SHOPIFY_ACCESS_TOKEN }}

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Debug Shopify ENV
        run: |
          echo "✅ SHOPIFY_STORE = $SHOPIFY_STORE"
          echo "✅ SHOPIFY_ACCESS_TOKEN length = ${#SHOPIFY_ACCESS_TOKEN} characters"

      - name: 📥 Fetch Google Sheets Data
        run: python scripts/fetch_google_sheets.py

      - name: 🛒 Fetch Shopify Orders
        run: python scripts/fetch_shopify_data.py

      - name: 🔗 Merge Data
        run: python scripts/merge_data.py

      - name: ✅ Commit and Push Updated Data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*.csv
          git diff --cached --quiet || git commit -m "🔄 Update merged data via GitHub Actions"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
