name: 🔄 Auto-Refresh Dashboard Data

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:        # Manual trigger button in GitHub UI

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🔄 Run data fetch and merge
        run: |
          python scripts/fetch_google_sheets.py
          python scripts/fetch_shopify_data.py
          python scripts/merge_data.py

      - name: 📝 Commit & push updated CSV
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/*.csv
          git commit -m "🔄 Auto-updated CSVs [bot]" || echo "No changes to commit"
          git push
